FEATURE_DESCRIPTIONS = {
 '2u_defix': 'Sent or received any amount of tokens tagged as DEFI any time',
 '2v_04': 'Sent or received any amount of tokens with M activity any time',
 '2w_1': 'Sent or received any amount of mainstream tokens any time',
 '2a_03u_defix': 'Sent or received an amount worth $100 - $1k of tokens tagged as DEFI any time',
 '2a_03v_04': 'Sent or received an amount worth $100 - $1k of tokens with M activity any time',
 '2a_03w_1': 'Sent or received an amount worth $100 - $1k of mainstream tokens any time',
 '2b_05': 'Sent or received an amount in the 40-50th percentile of any token any time',
 '2b_05u_defix': 'Sent or received an amount in the 40-50th percentile of tokens tagged as DEFI any time',
 '2b_05w_1': 'Sent or received an amount in the 40-50th percentile of mainstream tokens any time',
 '2r_': 'Received any amount of any token any time',
 '2r_u_defix': 'Received any amount of tokens tagged as DEFI any time',
 '2r_v_04': 'Received any amount of tokens with M activity any time',
 '2r_w_1': 'Received any amount of mainstream tokens any time',
 '2r_a_03': 'Received an amount worth $100 - $1k of any token any time',
 '2r_a_03u_defix': 'Received an amount worth $100 - $1k of tokens tagged as DEFI any time',
 '2r_a_03v_04': 'Received an amount worth $100 - $1k of tokens with M activity any time',
 '2r_a_03w_1': 'Received an amount worth $100 - $1k of mainstream tokens any time',
 '2r_b_05': 'Received an amount in the 40-50th percentile of any token any time',
 '2r_b_05u_defix': 'Received an amount in the 40-50th percentile of tokens tagged as DEFI any time',
 '2s_': 'Sent any amount of any token any time',
 '2s_u_defix': 'Sent any amount of tokens tagged as DEFI any time',
 '2s_v_04': 'Sent any amount of tokens with M activity any time',
 '2s_w_1': 'Sent any amount of mainstream tokens any time',
 '2s_a_03u_defix': 'Sent an amount worth $100 - $1k of tokens tagged as DEFI any time',
 '2s_a_03v_04': 'Sent an amount worth $100 - $1k of tokens with M activity any time',
 '2s_a_03w_1': 'Sent an amount worth $100 - $1k of mainstream tokens any time',
 '2s_b_05u_defix': 'Sent an amount in the 40-50th percentile of tokens tagged as DEFI any time',
 '2s_b_05v_04': 'Sent an amount in the 40-50th percentile of tokens with M activity any time',
 '2s_b_05w_1': 'Sent an amount in the 40-50th percentile of mainstream tokens any time',
 '2b_06': 'Sent or received an amount in the 50-60th percentile of any token any time',
 '2b_06u_defix': 'Sent or received an amount in the 50-60th percentile of tokens tagged as DEFI any time',
 '2b_06v_04': 'Sent or received an amount in the 50-60th percentile of tokens with M activity any time',
 '2b_06w_1': 'Sent or received an amount in the 50-60th percentile of mainstream tokens any time',
 '2r_b_06': 'Received an amount in the 50-60th percentile of any token any time',
 '2r_b_06u_defix': 'Received an amount in the 50-60th percentile of tokens tagged as DEFI any time',
 '2r_b_06v_04': 'Received an amount in the 50-60th percentile of tokens with M activity any time',
 '2t_x': 'Sent or received any amount of Ether any time',
 '2a_05t_x': 'Sent or received an amount worth $10k - $100k of Ether any time',
 '2b_10': 'Sent or received an amount in the +90th percentile of any token any time',
 '2b_10t_x': 'Sent or received an amount in the +90th percentile of Ether any time',
 '2s_t_x': 'Sent any amount of Ether any time',
 '2s_a_05': 'Sent an amount worth $10k - $100k of any token any time',
 '2s_b_10': 'Sent an amount in the +90th percentile of any token any time',
 '2s_b_10t_x': 'Sent an amount in the +90th percentile of Ether any time',
 '2r_t_x': 'Received any amount of Ether any time',
 '2r_a_05': 'Received an amount worth $10k - $100k of any token any time',
 '2r_a_05t_x': 'Received an amount worth $10k - $100k of Ether any time',
 '2r_b_10': 'Received an amount in the +90th percentile of any token any time',
 '2r_b_10t_x': 'Received an amount in the +90th percentile of Ether any time',
 '2a_02': 'Sent or received an amount worth $10 - $100 of any token any time',
 '2a_02v_04': 'Sent or received an amount worth $10 - $100 of tokens with M activity any time',
 '2a_02w_1': 'Sent or received an amount worth $10 - $100 of mainstream tokens any time',
 '2r_a_02': 'Received an amount worth $10 - $100 of any token any time',
 '2r_a_02w_1': 'Received an amount worth $10 - $100 of mainstream tokens any time',
 '2u_dexxx': 'Sent or received any amount of tokens tagged as DEX any time',
 '2a_01': 'Sent or received an amount worth <$10 of any token any time',
 '2a_01u_defix': 'Sent or received an amount worth <$10 of tokens tagged as DEFI any time',
 '2a_01w_1': 'Sent or received an amount worth <$10 of mainstream tokens any time',
 '2b_02': 'Sent or received an amount in the 10-20th percentile of any token any time',
 '2b_02u_defix': 'Sent or received an amount in the 10-20th percentile of tokens tagged as DEFI any time',
 '2b_02v_04': 'Sent or received an amount in the 10-20th percentile of tokens with M activity any time',
 '2r_u_dexxx': 'Received any amount of tokens tagged as DEX any time',
 '2r_a_01': 'Received an amount worth <$10 of any token any time',
 '2r_a_01u_defix': 'Received an amount worth <$10 of tokens tagged as DEFI any time',
 '2r_a_01w_1': 'Received an amount worth <$10 of mainstream tokens any time',
 '2r_b_02': 'Received an amount in the 10-20th percentile of any token any time',
 '2r_b_02v_04': 'Received an amount in the 10-20th percentile of tokens with M activity any time',
 '2v_05': 'Sent or received any amount of tokens with L activity any time',
 '2a_02v_05': 'Sent or received an amount worth $10 - $100 of tokens with L activity any time',
 '2b_03': 'Sent or received an amount in the 20-30th percentile of any token any time',
 '2b_03u_defix': 'Sent or received an amount in the 20-30th percentile of tokens tagged as DEFI any time',
 '2b_03v_05': 'Sent or received an amount in the 20-30th percentile of tokens with L activity any time',
 '2b_03w_1': 'Sent or received an amount in the 20-30th percentile of mainstream tokens any time',
 '2s_v_05': 'Sent any amount of tokens with L activity any time',
 '2s_a_02': 'Sent an amount worth $10 - $100 of any token any time',
 '2s_a_02v_05': 'Sent an amount worth $10 - $100 of tokens with L activity any time',
 '2s_a_02w_1': 'Sent an amount worth $10 - $100 of mainstream tokens any time',
 '2s_b_03': 'Sent an amount in the 20-30th percentile of any token any time',
 '2s_b_03u_defix': 'Sent an amount in the 20-30th percentile of tokens tagged as DEFI any time',
 '2s_b_03w_1': 'Sent an amount in the 20-30th percentile of mainstream tokens any time',
 '2r_v_05': 'Received any amount of tokens with L activity any time',
 '2r_b_03w_1': 'Received an amount in the 20-30th percentile of mainstream tokens any time',
 '2t_c02aaa39b223fe8': 'Sent or received any amount of WETH (WETH) any time',
 '2a_05w_1': 'Sent or received an amount worth $10k - $100k of mainstream tokens any time',
 '2b_07': 'Sent or received an amount in the 60-70th percentile of any token any time',
 '2b_07v_05': 'Sent or received an amount in the 60-70th percentile of tokens with L activity any time',
 '2b_07w_1': 'Sent or received an amount in the 60-70th percentile of mainstream tokens any time',
 '2s_t_c02aaa39b223fe8': 'Sent any amount of WETH (WETH) any time',
 '2s_a_05t_c02aaa39b223fe8': 'Sent an amount worth $10k - $100k of WETH (WETH) any time',
 '2s_a_05v_05': 'Sent an amount worth $10k - $100k of tokens with L activity any time',
 '2s_a_05w_1': 'Sent an amount worth $10k - $100k of mainstream tokens any time',
 '2s_b_07': 'Sent an amount in the 60-70th percentile of any token any time',
 '2s_b_07w_1': 'Sent an amount in the 60-70th percentile of mainstream tokens any time',
 '2r_t_c02aaa39b223fe8': 'Received any amount of WETH (WETH) any time',
 '2r_a_05w_1': 'Received an amount worth $10k - $100k of mainstream tokens any time',
 '2r_b_07': 'Received an amount in the 60-70th percentile of any token any time',
 '2r_b_07w_1': 'Received an amount in the 60-70th percentile of mainstream tokens any time',
 '2u_stabl': 'Sent or received any amount of tokens tagged as STABLE any time',
 '2w_2': 'Sent or received any amount of exotic tokens any time',
 '2s_u_stabl': 'Sent any amount of tokens tagged as STABLE any time',
 '2s_w_2': 'Sent any amount of exotic tokens any time',
 '2r_u_stabl': 'Received any amount of tokens tagged as STABLE any time',
 '2r_w_2': 'Received any amount of exotic tokens any time',
 '2s_a_02v_04': 'Sent an amount worth $10 - $100 of tokens with M activity any time',
 '2s_b_06': 'Sent an amount in the 50-60th percentile of any token any time',
 '2s_b_06u_defix': 'Sent an amount in the 50-60th percentile of tokens tagged as DEFI any time',
 '2s_b_06w_1': 'Sent an amount in the 50-60th percentile of mainstream tokens any time',
 '2v_06': 'Sent or received any amount of tokens with XL activity any time',
 '2a_04': 'Sent or received an amount worth $1k - $10k of any token any time',
 '2a_04u_defix': 'Sent or received an amount worth $1k - $10k of tokens tagged as DEFI any time',
 '2a_04w_1': 'Sent or received an amount worth $1k - $10k of mainstream tokens any time',
 '2b_09': 'Sent or received an amount in the 80-90th percentile of any token any time',
 '2b_09v_06': 'Sent or received an amount in the 80-90th percentile of tokens with XL activity any time',
 '2b_09w_1': 'Sent or received an amount in the 80-90th percentile of mainstream tokens any time',
 '2s_v_06': 'Sent any amount of tokens with XL activity any time',
 '2s_a_04': 'Sent an amount worth $1k - $10k of any token any time',
 '2s_a_04u_dexxx': 'Sent an amount worth $1k - $10k of tokens tagged as DEX any time',
 '2s_a_04u_defix': 'Sent an amount worth $1k - $10k of tokens tagged as DEFI any time',
 '2s_a_04v_06': 'Sent an amount worth $1k - $10k of tokens with XL activity any time',
 '2s_a_04w_1': 'Sent an amount worth $1k - $10k of mainstream tokens any time',
 '2s_b_09': 'Sent an amount in the 80-90th percentile of any token any time',
 '2s_b_09u_dexxx': 'Sent an amount in the 80-90th percentile of tokens tagged as DEX any time',
 '2s_b_09u_defix': 'Sent an amount in the 80-90th percentile of tokens tagged as DEFI any time',
 '2s_b_09v_06': 'Sent an amount in the 80-90th percentile of tokens with XL activity any time',
 '2s_b_09w_1': 'Sent an amount in the 80-90th percentile of mainstream tokens any time',
 '2r_v_06': 'Received any amount of tokens with XL activity any time',
 '2r_a_04u_defix': 'Received an amount worth $1k - $10k of tokens tagged as DEFI any time',
 '2r_b_09': 'Received an amount in the 80-90th percentile of any token any time',
 '2r_b_09u_dexxx': 'Received an amount in the 80-90th percentile of tokens tagged as DEX any time',
 '2r_b_09v_06': 'Received an amount in the 80-90th percentile of tokens with XL activity any time',
 '2r_b_09w_1': 'Received an amount in the 80-90th percentile of mainstream tokens any time',
 '2t_57ab1ec28d12970': 'Sent or received any amount of SUSD (SUSD) any time',
 '2a_03u_stabl': 'Sent or received an amount worth $100 - $1k of tokens tagged as STABLE any time',
 '2b_04': 'Sent or received an amount in the 30-40th percentile of any token any time',
 '2b_04u_defix': 'Sent or received an amount in the 30-40th percentile of tokens tagged as DEFI any time',
 '2b_04v_04': 'Sent or received an amount in the 30-40th percentile of tokens with M activity any time',
 '2b_04w_1': 'Sent or received an amount in the 30-40th percentile of mainstream tokens any time',
 '2s_a_03u_stabl': 'Sent an amount worth $100 - $1k of tokens tagged as STABLE any time',
 '2s_b_04': 'Sent an amount in the 30-40th percentile of any token any time',
 '2s_b_04u_stabl': 'Sent an amount in the 30-40th percentile of tokens tagged as STABLE any time',
 '2s_b_04w_1': 'Sent an amount in the 30-40th percentile of mainstream tokens any time',
 '2r_a_03u_stabl': 'Received an amount worth $100 - $1k of tokens tagged as STABLE any time',
 '2r_b_04u_defix': 'Received an amount in the 30-40th percentile of tokens tagged as DEFI any time',
 '2r_b_04w_1': 'Received an amount in the 30-40th percentile of mainstream tokens any time',
 '2t_6b175474e89094c': 'Sent or received any amount of DAI (DAI) any time',
 '2a_03v_06': 'Sent or received an amount worth $100 - $1k of tokens with XL activity any time',
 '2s_t_6b175474e89094c': 'Sent any amount of DAI (DAI) any time',
 '2s_a_03v_06': 'Sent an amount worth $100 - $1k of tokens with XL activity any time',
 '2r_t_6b175474e89094c': 'Received any amount of DAI (DAI) any time',
 '2r_a_03v_06': 'Received an amount worth $100 - $1k of tokens with XL activity any time',
 '2a_04t_x': 'Sent or received an amount worth $1k - $10k of Ether any time',
 '2b_08': 'Sent or received an amount in the 70-80th percentile of any token any time',
 '2b_08t_x': 'Sent or received an amount in the 70-80th percentile of Ether any time',
 '2r_a_04t_x': 'Received an amount worth $1k - $10k of Ether any time',
 '2r_b_08': 'Received an amount in the 70-80th percentile of any token any time',
 '2s_a_01u_defix': 'Sent an amount worth <$10 of tokens tagged as DEFI any time',
 '2s_a_01v_04': 'Sent an amount worth <$10 of tokens with M activity any time',
 '2s_a_01w_1': 'Sent an amount worth <$10 of mainstream tokens any time',
 '2s_b_02': 'Sent an amount in the 10-20th percentile of any token any time',
 '2t_a0b86991c6218b3': 'Sent or received any amount of USD COIN (USDC) any time',
 '2a_02u_stabl': 'Sent or received an amount worth $10 - $100 of tokens tagged as STABLE any time',
 '2a_02v_06': 'Sent or received an amount worth $10 - $100 of tokens with XL activity any time',
 '2r_t_a0b86991c6218b3': 'Received any amount of USD COIN (USDC) any time',
 '2r_a_02v_06': 'Received an amount worth $10 - $100 of tokens with XL activity any time',
 '2v_03': 'Sent or received any amount of tokens with S activity any time',
 '2a_02v_03': 'Sent or received an amount worth $10 - $100 of tokens with S activity any time',
 '2s_v_03': 'Sent any amount of tokens with S activity any time',
 '2b_01': 'Sent or received an amount in the <10th percentile of any token any time',
 '2b_01v_04': 'Sent or received an amount in the <10th percentile of tokens with M activity any time',
 '2b_01w_1': 'Sent or received an amount in the <10th percentile of mainstream tokens any time',
 '2s_b_01': 'Sent an amount in the <10th percentile of any token any time',
 '2s_b_01u_defix': 'Sent an amount in the <10th percentile of tokens tagged as DEFI any time',
 '2s_b_01w_1': 'Sent an amount in the <10th percentile of mainstream tokens any time',
 '2b_07u_defix': 'Sent or received an amount in the 60-70th percentile of tokens tagged as DEFI any time',
 '2s_b_07u_defix': 'Sent an amount in the 60-70th percentile of tokens tagged as DEFI any time',
 '2r_a_04v_05': 'Received an amount worth $1k - $10k of tokens with L activity any time',
 '2b_06v_05': 'Sent or received an amount in the 50-60th percentile of tokens with L activity any time',
 '2r_b_06v_05': 'Received an amount in the 50-60th percentile of tokens with L activity any time',
 '2a_05u_defix': 'Sent or received an amount worth $10k - $100k of tokens tagged as DEFI any time',
 '2b_10u_defix': 'Sent or received an amount in the +90th percentile of tokens tagged as DEFI any time',
 '2b_10v_05': 'Sent or received an amount in the +90th percentile of tokens with L activity any time',
 '2b_10w_1': 'Sent or received an amount in the +90th percentile of mainstream tokens any time',
 '2s_a_05u_defix': 'Sent an amount worth $10k - $100k of tokens tagged as DEFI any time',
 '2s_b_10u_defix': 'Sent an amount in the +90th percentile of tokens tagged as DEFI any time',
 '2s_b_10v_05': 'Sent an amount in the +90th percentile of tokens with L activity any time',
 '2s_b_10w_1': 'Sent an amount in the +90th percentile of mainstream tokens any time',
 '2r_a_05u_defix': 'Received an amount worth $10k - $100k of tokens tagged as DEFI any time',
 '2r_b_10u_defix': 'Received an amount in the +90th percentile of tokens tagged as DEFI any time',
 '2r_b_10v_05': 'Received an amount in the +90th percentile of tokens with L activity any time',
 '2t_35a18000230da77': 'Sent or received any amount of CUNI (CUNI) any time',
 '2a_04v_04': 'Sent or received an amount worth $1k - $10k of tokens with M activity any time',
 '2b_08u_defix': 'Sent or received an amount in the 70-80th percentile of tokens tagged as DEFI any time',
 '2b_08v_04': 'Sent or received an amount in the 70-80th percentile of tokens with M activity any time',
 '2b_08w_1': 'Sent or received an amount in the 70-80th percentile of mainstream tokens any time',
 '2s_a_04v_04': 'Sent an amount worth $1k - $10k of tokens with M activity any time',
 '2s_b_08': 'Sent an amount in the 70-80th percentile of any token any time',
 '2r_a_04v_04': 'Received an amount worth $1k - $10k of tokens with M activity any time',
 '2r_b_08u_defix': 'Received an amount in the 70-80th percentile of tokens tagged as DEFI any time',
 '2r_b_08v_04': 'Received an amount in the 70-80th percentile of tokens with M activity any time',
 '2r_b_08w_1': 'Received an amount in the 70-80th percentile of mainstream tokens any time',
 '2a_04t_a0b86991c6218b3': 'Sent or received an amount worth $1k - $10k of USD COIN (USDC) any time',
 '2a_04u_stabl': 'Sent or received an amount worth $1k - $10k of tokens tagged as STABLE any time',
 '2b_09t_a0b86991c6218b3': 'Sent or received an amount in the 80-90th percentile of USD COIN (USDC) any time',
 '2b_09u_stabl': 'Sent or received an amount in the 80-90th percentile of tokens tagged as STABLE any time',
 '2s_a_04t_a0b86991c6218b3': 'Sent an amount worth $1k - $10k of USD COIN (USDC) any time',
 '2s_a_04u_stabl': 'Sent an amount worth $1k - $10k of tokens tagged as STABLE any time',
 '2s_b_09t_a0b86991c6218b3': 'Sent an amount in the 80-90th percentile of USD COIN (USDC) any time',
 '2s_b_09u_stabl': 'Sent an amount in the 80-90th percentile of tokens tagged as STABLE any time',
 '2r_a_04u_stabl': 'Received an amount worth $1k - $10k of tokens tagged as STABLE any time',
 '2a_01v_05': 'Sent or received an amount worth <$10 of tokens with L activity any time',
 '2r_b_01': 'Received an amount in the <10th percentile of any token any time',
 '2r_b_01w_1': 'Received an amount in the <10th percentile of mainstream tokens any time',
 '2b_08v_05': 'Sent or received an amount in the 70-80th percentile of tokens with L activity any time',
 '2s_b_08u_dexxx': 'Sent an amount in the 70-80th percentile of tokens tagged as DEX any time',
 '2s_b_08v_05': 'Sent an amount in the 70-80th percentile of tokens with L activity any time',
 '2a_04t_c02aaa39b223fe8': 'Sent or received an amount worth $1k - $10k of WETH (WETH) any time',
 '2b_05v_05': 'Sent or received an amount in the 40-50th percentile of tokens with L activity any time',
 '2r_b_05v_05': 'Received an amount in the 40-50th percentile of tokens with L activity any time',
 '2a_03v_03': 'Sent or received an amount worth $100 - $1k of tokens with S activity any time',
 '2s_a_03u_dexxx': 'Sent an amount worth $100 - $1k of tokens tagged as DEX any time',
 '2s_a_03v_03': 'Sent an amount worth $100 - $1k of tokens with S activity any time',
 '2r_v_03': 'Received any amount of tokens with S activity any time',
 '2r_a_03u_dexxx': 'Received an amount worth $100 - $1k of tokens tagged as DEX any time',
 '2a_05u_stabl': 'Sent or received an amount worth $10k - $100k of tokens tagged as STABLE any time',
 '2a_05v_04': 'Sent or received an amount worth $10k - $100k of tokens with M activity any time',
 '2b_08u_stabl': 'Sent or received an amount in the 70-80th percentile of tokens tagged as STABLE any time',
 '2s_a_05u_stabl': 'Sent an amount worth $10k - $100k of tokens tagged as STABLE any time',
 '2s_a_05v_04': 'Sent an amount worth $10k - $100k of tokens with M activity any time',
 '2s_b_08u_stabl': 'Sent an amount in the 70-80th percentile of tokens tagged as STABLE any time',
 '2r_a_05u_stabl': 'Received an amount worth $10k - $100k of tokens tagged as STABLE any time',
 '2r_a_05v_04': 'Received an amount worth $10k - $100k of tokens with M activity any time',
 '2b_08v_06': 'Sent or received an amount in the 70-80th percentile of tokens with XL activity any time',
 '2s_b_08v_06': 'Sent an amount in the 70-80th percentile of tokens with XL activity any time',
 '2r_b_09t_x': 'Received an amount in the 80-90th percentile of Ether any time',
 '2a_05v_06': 'Sent or received an amount worth $10k - $100k of tokens with XL activity any time',
 '2b_10t_a0b86991c6218b3': 'Sent or received an amount in the +90th percentile of USD COIN (USDC) any time',
 '2b_10u_stabl': 'Sent or received an amount in the +90th percentile of tokens tagged as STABLE any time',
 '2b_10v_06': 'Sent or received an amount in the +90th percentile of tokens with XL activity any time',
 '2s_a_05t_a0b86991c6218b3': 'Sent an amount worth $10k - $100k of USD COIN (USDC) any time',
 '2s_a_05v_06': 'Sent an amount worth $10k - $100k of tokens with XL activity any time',
 '2s_b_10u_stabl': 'Sent an amount in the +90th percentile of tokens tagged as STABLE any time',
 '2s_b_10v_06': 'Sent an amount in the +90th percentile of tokens with XL activity any time',
 '2r_a_05t_a0b86991c6218b3': 'Received an amount worth $10k - $100k of USD COIN (USDC) any time',
 '2r_b_10u_stabl': 'Received an amount in the +90th percentile of tokens tagged as STABLE any time',
 '2b_07v_06': 'Sent or received an amount in the 60-70th percentile of tokens with XL activity any time',
 '2r_b_07u_stabl': 'Received an amount in the 60-70th percentile of tokens tagged as STABLE any time',
 '2r_b_07v_06': 'Received an amount in the 60-70th percentile of tokens with XL activity any time',
 '2s_a_04t_x': 'Sent an amount worth $1k - $10k of Ether any time',
 '2b_09v_05': 'Sent or received an amount in the 80-90th percentile of tokens with L activity any time',
 '2s_b_09v_05': 'Sent an amount in the 80-90th percentile of tokens with L activity any time',
 '2r_b_09v_05': 'Received an amount in the 80-90th percentile of tokens with L activity any time',
 '2b_07v_04': 'Sent or received an amount in the 60-70th percentile of tokens with M activity any time',
 '2b_09v_04': 'Sent or received an amount in the 80-90th percentile of tokens with M activity any time',
 '2s_b_09v_04': 'Sent an amount in the 80-90th percentile of tokens with M activity any time',
 '2r_a_05t_6b175474e89094c': 'Received an amount worth $10k - $100k of DAI (DAI) any time',
 '2a_03t_x': 'Sent or received an amount worth $100 - $1k of Ether any time',
 '2r_a_03t_x': 'Received an amount worth $100 - $1k of Ether any time',
 '2r_b_05t_x': 'Received an amount in the 40-50th percentile of Ether any time',
 '2a_03v_05': 'Sent or received an amount worth $100 - $1k of tokens with L activity any time',
 '2b_06u_dexxx': 'Sent or received an amount in the 50-60th percentile of tokens tagged as DEX any time',
 '2s_a_03v_05': 'Sent an amount worth $100 - $1k of tokens with L activity any time',
 '2r_a_03v_05': 'Received an amount worth $100 - $1k of tokens with L activity any time',
 '2v_02': 'Sent or received any amount of tokens with XS activity any time',
 '2a_03v_02': 'Sent or received an amount worth $100 - $1k of tokens with XS activity any time',
 '2s_v_02': 'Sent any amount of tokens with XS activity any time',
 '2s_a_03v_02': 'Sent an amount worth $100 - $1k of tokens with XS activity any time',
 '2t_6f40d4a6237c257': 'Sent or received any amount of INSTADAPP (INST) any time',
 '2b_10t_6b175474e89094c': 'Sent or received an amount in the +90th percentile of DAI (DAI) any time',
 '2u_nftxx': 'Sent or received any amount of tokens tagged as NFT any time',
 '2s_u_nftxx': 'Sent any amount of tokens tagged as NFT any time',
 '2t_dac17f958d2ee52': 'Sent or received any amount of TETHER USD (USDT) any time',
 '2v_07': 'Sent or received any amount of tokens with XXL activity any time',
 '2s_v_07': 'Sent any amount of tokens with XXL activity any time',
 '2r_v_07': 'Received any amount of tokens with XXL activity any time',
 '2b_10v_04': 'Sent or received an amount in the +90th percentile of tokens with M activity any time',
 '2s_b_10v_04': 'Sent an amount in the +90th percentile of tokens with M activity any time',
 '2r_b_10v_04': 'Received an amount in the +90th percentile of tokens with M activity any time',
 '2t_4ddc2d193948926': 'Sent or received any amount of CETH (CETH) any time',
 '2r_t_4ddc2d193948926': 'Received any amount of CETH (CETH) any time',
 '2a_02t_x': 'Sent or received an amount worth $10 - $100 of Ether any time',
 '2s_a_02t_x': 'Sent an amount worth $10 - $100 of Ether any time',
 '2r_b_07t_x': 'Received an amount in the 60-70th percentile of Ether any time',
 '2b_01t_a0b86991c6218b3': 'Sent or received an amount in the <10th percentile of USD COIN (USDC) any time',
 '2b_01u_stabl': 'Sent or received an amount in the <10th percentile of tokens tagged as STABLE any time',
 '2s_a_02u_stabl': 'Sent an amount worth $10 - $100 of tokens tagged as STABLE any time',
 '2s_b_01u_stabl': 'Sent an amount in the <10th percentile of tokens tagged as STABLE any time',
 '2r_b_01u_stabl': 'Received an amount in the <10th percentile of tokens tagged as STABLE any time',
 '2r_a_02t_x': 'Received an amount worth $10 - $100 of Ether any time',
 '2b_02t_x': 'Sent or received an amount in the 10-20th percentile of Ether any time',
 '2b_03v_04': 'Sent or received an amount in the 20-30th percentile of tokens with M activity any time',
 '2r_b_03v_04': 'Received an amount in the 20-30th percentile of tokens with M activity any time',
 '2b_04t_x': 'Sent or received an amount in the 30-40th percentile of Ether any time',
 '2a_03t_dac17f958d2ee52': 'Sent or received an amount worth $100 - $1k of TETHER USD (USDT) any time',
 '2b_05v_06': 'Sent or received an amount in the 40-50th percentile of tokens with XL activity any time',
 '2b_06u_stabl': 'Sent or received an amount in the 50-60th percentile of tokens tagged as STABLE any time',
 '2a_06': 'Sent or received an amount worth $100k - $1M of any token any time',
 '2s_a_06': 'Sent an amount worth $100k - $1M of any token any time',
 '2r_a_06': 'Received an amount worth $100k - $1M of any token any time',
 '2r_a_06t_x': 'Received an amount worth $100k - $1M of Ether any time',
 '2s_b_08t_a0b86991c6218b3': 'Sent an amount in the 70-80th percentile of USD COIN (USDC) any time',
 '2a_06w_1': 'Sent or received an amount worth $100k - $1M of mainstream tokens any time',
 '2s_a_06w_1': 'Sent an amount worth $100k - $1M of mainstream tokens any time',
 '2r_a_06w_1': 'Received an amount worth $100k - $1M of mainstream tokens any time',
 '2s_b_06v_06': 'Sent an amount in the 50-60th percentile of tokens with XL activity any time',
 '2a_04t_dac17f958d2ee52': 'Sent or received an amount worth $1k - $10k of TETHER USD (USDT) any time',
 '2s_b_03v_04': 'Sent an amount in the 20-30th percentile of tokens with M activity any time',
 '2u_oracl': 'Sent or received any amount of tokens tagged as ORACLE any time',
 '2r_b_07v_04': 'Received an amount in the 60-70th percentile of tokens with M activity any time',
 '2r_t_d533a949740bb33': 'Received any amount of CURVE DAO TOKEN (CRV) any time',
 '2a_06u_defix': 'Sent or received an amount worth $100k - $1M of tokens tagged as DEFI any time',
 '2a_06v_05': 'Sent or received an amount worth $100k - $1M of tokens with L activity any time',
 '2s_a_06u_defix': 'Sent an amount worth $100k - $1M of tokens tagged as DEFI any time',
 '2r_a_06u_defix': 'Received an amount worth $100k - $1M of tokens tagged as DEFI any time',
 '2t_2260fac5e5542a7': 'Sent or received any amount of WRAPPED BITCOIN (WBTC) any time',
 '2u_bitco': 'Sent or received any amount of tokens tagged as BITCOIN any time',
 '2a_03u_nftxx': 'Sent or received an amount worth $100 - $1k of tokens tagged as NFT any time',
 '2b_09u_nftxx': 'Sent or received an amount in the 80-90th percentile of tokens tagged as NFT any time',
 '2s_t_2260fac5e5542a7': 'Sent any amount of WRAPPED BITCOIN (WBTC) any time',
 '2s_a_03t_x': 'Sent an amount worth $100 - $1k of Ether any time',
 '2s_b_07t_x': 'Sent an amount in the 60-70th percentile of Ether any time',
 '2a_04v_03': 'Sent or received an amount worth $1k - $10k of tokens with S activity any time',
 '2s_a_04v_03': 'Sent an amount worth $1k - $10k of tokens with S activity any time',
 '2r_a_04v_03': 'Received an amount worth $1k - $10k of tokens with S activity any time',
 '2s_b_05t_x': 'Sent an amount in the 40-50th percentile of Ether any time',
 '2t_1982b2f5814301d': 'Sent or received any amount of AAVE INTEREST BEARING STETH (ASTETH) any time',
 '2t_619beb58998ed22': 'Sent or received any amount of AAVE VARIABLE DEBT BEARING USDC (VARIABLEDEBTUSDC) any time',
 '2r_t_619beb58998ed22': 'Received any amount of AAVE VARIABLE DEBT BEARING USDC (VARIABLEDEBTUSDC) any time',
 '2u_ethst': 'Sent or received any amount of tokens tagged as ETHSTAKING any time',
 '2r_t_ae7ab96520de3a1': 'Received any amount of LIDO STAKED ETHER (STETH) any time',
 '2r_u_ethst': 'Received any amount of tokens tagged as ETHSTAKING any time',
 '2t_030ba81f1c18d28': 'Sent or received any amount of AAVE WETH (AWETH) any time',
 '2r_t_030ba81f1c18d28': 'Received any amount of AAVE WETH (AWETH) any time',
 '2s_t_619beb58998ed22': 'Sent any amount of AAVE VARIABLE DEBT BEARING USDC (VARIABLEDEBTUSDC) any time',
 '2w_3': 'Sent or received any amount of NFTs any time',
 '2r_w_3': 'Received any amount of NFTs any time',
 '2r_a_06v_04': 'Received an amount worth $100k - $1M of tokens with M activity any time',
 '2a_06v_06': 'Sent or received an amount worth $100k - $1M of tokens with XL activity any time',
 '2s_a_01u_stabl': 'Sent an amount worth <$10 of tokens tagged as STABLE any time',
 '2r_b_05u_dexxx': 'Received an amount in the 40-50th percentile of tokens tagged as DEX any time',
 '2s_b_05v_05': 'Sent an amount in the 40-50th percentile of tokens with L activity any time',
 '2s_b_09u_nftxx': 'Sent an amount in the 80-90th percentile of tokens tagged as NFT any time',
 '2s_t_4ddc2d193948926': 'Sent any amount of CETH (CETH) any time',
 '2s_a_04u_nftxx': 'Sent an amount worth $1k - $10k of tokens tagged as NFT any time',
 '2a_07': 'Sent or received an amount worth $1M - $10M of any token any time',
 '2s_a_07': 'Sent an amount worth $1M - $10M of any token any time',
 '2s_b_03v_06': 'Sent an amount in the 20-30th percentile of tokens with XL activity any time',
 '2t_1412eca9dc7daef': 'Sent or received any amount of A68.NET (A68.NET) any time',
 '2t_bcca60bb6193408': 'Sent or received any amount of AAVE USDC (AUSDC) any time',
 '2r_t_bcca60bb6193408': 'Received any amount of AAVE USDC (AUSDC) any time',
 '2r_a_03v_07': 'Received an amount worth $100 - $1k of tokens with XXL activity any time',
 '2s_b_06t_x': 'Sent an amount in the 50-60th percentile of Ether any time',
 '2t_f650c3d88d12db8': 'Sent or received any amount of CUSDT (CUSDT) any time',
 '2t_5d3a536e4d6dbd6': 'Sent or received any amount of CDAI (CDAI) any time',
 '2r_t_5d3a536e4d6dbd6': 'Received any amount of CDAI (CDAI) any time',
 '2r_a_07v_06': 'Received an amount worth $1M - $10M of tokens with XL activity any time',
 '2t_a64bd6c70cb9051': 'Sent or received any amount of AAVE LINK (ALINK) any time',
 '2r_t_a64bd6c70cb9051': 'Received any amount of AAVE LINK (ALINK) any time',
 '2b_10t_c02aaa39b223fe8': 'Sent or received an amount in the +90th percentile of WETH (WETH) any time',
 '2b_10u_nftxx': 'Sent or received an amount in the +90th percentile of tokens tagged as NFT any time',
 '2s_b_10u_nftxx': 'Sent an amount in the +90th percentile of tokens tagged as NFT any time',
 '2s_b_09t_2260fac5e5542a7': 'Sent an amount in the 80-90th percentile of WRAPPED BITCOIN (WBTC) any time',
 '2t_3472a5a71965499': 'Sent or received any amount of BADGER DAO (BADGER) any time',
 '2r_b_10t_c02aaa39b223fe8': 'Received an amount in the +90th percentile of WETH (WETH) any time',
 '2r_b_10t_4ddc2d193948926': 'Received an amount in the +90th percentile of CETH (CETH) any time',
 '2s_a_06u_dexxx': 'Sent an amount worth $100k - $1M of tokens tagged as DEX any time',
 '2s_t_c11b1268c1a384e': 'Sent any amount of CWBTC (CWBTC) any time',
 '2t_80fb784b7ed6673': 'Sent or received any amount of AAVE [OLD] (LEND) any time',
 '2t_7d1afa7b718fb89': 'Sent or received any amount of MATIC NETWORK (MATIC) any time',
 '2r_b_03u_polka': 'Received an amount in the 20-30th percentile of tokens tagged as POLKADOT any time',
 '2t_89d24a6b4ccb1b6': 'Sent or received any amount of SAI (SAI) any time',
 '2r_t_89d24a6b4ccb1b6': 'Received any amount of SAI (SAI) any time',
 '2s_t_9f8f72aa9304c8b': 'Sent any amount of MAKER (MKR) any time',
 '2s_t_80fb784b7ed6673': 'Sent any amount of AAVE [OLD] (LEND) any time',
 '2t_4da27a545c0c5b7': 'Sent or received any amount of STAKED AAVE (STKAAVE) any time',
 '2r_t_3b484b82567a09e': 'Received any amount of OPENDAO (SOS) any time',
 '2b_01u_datax': 'Sent or received an amount in the <10th percentile of tokens tagged as DATA any time',
 '2s_a_03t_dac17f958d2ee52': 'Sent an amount worth $100 - $1k of TETHER USD (USDT) any time',
 '2a_03t_4ddc2d193948926': 'Sent or received an amount worth $100 - $1k of CETH (CETH) any time',
 '2t_b3319f5d18bc0d8': 'Sent or received any amount of C0X (CZRX) any time',
 '2t_6c3c78838c761c6': 'Sent or received any amount of AAVE VARIABLE DEBT BEARING DAI (VARIABLEDEBTDAI) any time',
 '2t_9ff58f4ffb29fa2': 'Sent or received any amount of AAVE WBTC (AWBTC) any time',
 '2r_t_9ff58f4ffb29fa2': 'Received any amount of AAVE WBTC (AWBTC) any time',
 '2t_3a3a65aab0dd2a1': 'Sent or received any amount of AAVE ETH (AETH) any time',
 '2r_t_3a3a65aab0dd2a1': 'Received any amount of AAVE ETH (AETH) any time',
 '2s_t_3a3a65aab0dd2a1': 'Sent any amount of AAVE ETH (AETH) any time',
 '2r_a_04t_ae7ab96520de3a1': 'Received an amount worth $1k - $10k of LIDO STAKED ETHER (STETH) any time',
 '2a_04t_4ddc2d193948926': 'Sent or received an amount worth $1k - $10k of CETH (CETH) any time',
 '2r_a_04t_4ddc2d193948926': 'Received an amount worth $1k - $10k of CETH (CETH) any time',
 '2r_a_05t_3a3a65aab0dd2a1': 'Received an amount worth $10k - $100k of AAVE ETH (AETH) any time',
 '2s_t_531842cebbdd378': 'Sent any amount of AAVE VARIABLE DEBT BEARING USDT (VARIABLEDEBTUSDT) any time',
 '2s_t_ccf4429db6322d5': 'Sent any amount of COMPOUND WRAPPED BTC (CWBTC) any time',
 '2s_t_030ba81f1c18d28': 'Sent any amount of AAVE WETH (AWETH) any time',
 '2s_t_9ff58f4ffb29fa2': 'Sent any amount of AAVE WBTC (AWBTC) any time',
 '2s_t_ffc97d72e13e010': 'Sent any amount of AAVE AAVE (AAAVE) any time',
 '2s_t_a06bc25b5805d5f': 'Sent any amount of ~0xa06bc25b5805d5f... any time',
 '2s_t_6c3c78838c761c6': 'Sent any amount of AAVE VARIABLE DEBT BEARING DAI (VARIABLEDEBTDAI) any time',
 '2s_a_04v_02': 'Sent an amount worth $1k - $10k of tokens with XS activity any time',
 '2s_a_02t_3b484b82567a09e': 'Sent an amount worth $10 - $100 of OPENDAO (SOS) any time',
 '2a_03t_35a18000230da77': 'Sent or received an amount worth $100 - $1k of CUNI (CUNI) any time',
 '2s_a_03t_ae7ab96520de3a1': 'Sent an amount worth $100 - $1k of LIDO STAKED ETHER (STETH) any time'
}